#!/bin/bash
script_path=$(dirname "$0")
FILE_NUM=32
for((i=1;i<=FILE_NUM;i++))
do
	if [ -f $script_path"/G$i" ]; then 
	rm -rf $script_path"/G$i"      
	touch $script_path"/G$i" 
	else
	touch $script_path"/G$i" 
	fi
done

cat $script_path"/test_small" | while read line
do 
	lineLength=${#line}
for((j=1;j<=lineLength;j++))
	do
		echo ${line:j-1:1}>>$script_path"/G$j"
	done
done 
echo -n "Finish filling out $FILE_NUM files. "
echo "The testcase is constructed!"
exit 0
