#!/bin/bash
script_path=$(dirname "$0")
if [ -z "$1" ] || [ -z "$2" ]
then
	echo "Run as generateTest model numInputs"
	echo "Eg: generateTest c2670 200"
	#echo "Or (for all directories): generateTest all 200"
	exit 1
else
	if [ -d "$1" ]
	then
		cd $1
		NUM_INPUTS=$(<input_num)
		NUM_TESTS=$2
	else
		echo "Make sure the first perameter is a directory..."
		exit 1
	fi
fi

rm G*

for ((i=0;i<NUM_TESTS;i++))
do
	for ((j=1;j<=NUM_INPUTS;j++))
	do
		echo $[ ($RANDOM % 2) ] >>$script_path"/G$j"
	done
done 
echo -n "Finish filling out $NUM_INPUTS files. "
echo "The testcase is constructed!"
exit 0
