#!/bin/bash

# Simulation command line.
PHOLD="./pholdSim -configuration configuration.config -simulate LargePHOLD -simulateUntil 7000"
RAID="./raidSim -configuration configuration.config -simulate LargeRaid"
SMMP="./smmpSim -configuration configuration.config -simulate LargeSMMP"

# These define the configuration options.
SIMULATION_TYPE=TimeWarp
EVENT_LIST_TYPE=Default
OBJECT_QUEUE_TYPE=LockedQueue
NUMBER_OF_BUCKETS=5
BUCKET_WIDTH=10
NUMBER_OF_WORKER_THREADS=4
SIMULATION_MANAGER_DOES_WORK=False
COMUNICATION_MANAGER_TYPE=TCPSelect
NODE_INFORMATION=n001,n002,n003,n004,n005,n006,n007,n008,n009,n010,n011,n012,n013,n014,n015
STATE_MANAGER_TYPE=Periodic
STATE_MANAGER_PERIOD=10
OUTPUT_MANAGER_TYPE=Aggressive
OUTPUT_MANAGER_ANTI=Default
GVT_MANAGER_TYPE=Mattern
GVT_MANAGER_PERIOD=1000
FOSSIL_MANAGER_TYPE=None
FOSSIL_MANAGER_CHKPT=10000
FOSSIL_MANAGER_MIN=64
FOSSIL_MANAGER_MAX=100
FOSSIL_MANAGER_DEFAULT=2000
FOSSIL_MANAGER_RISK=0.99

# This function writes the configuration file.
function writeConfiguration {
	echo "Simulation : $SIMULATION_TYPE" > ~/configuration.config
	echo "TimeWarp {" >> ~/configuration.config
	echo "Scheduler { Type : Default  }" >> ~/configuration.config
	echo "EventList {Type : $EVENT_LIST_TYPE" >> ~/configuration.config
	echo "Organization : Decentralized }" >> ~/configuration.config
	echo "ObjectQueue {Type : $OBJECT_QUEUE_TYPE" >> ~/configuration.config
	echo "NumberOfBuckets : $NUMBER_OF_BUCKETS " >> ~/configuration.config
	echo "BucketWidth : $BUCKET_WIDTH  }" >> ~/configuration.config
	echo "ThreadControl { WorkerThreadCount : $NUMBER_OF_WORKER_THREADS" >> ~/configuration.config
	echo "SimulationManagerDoesWork : $SIMULATION_MANAGER_DOES_WORK }" >> ~/configuration.config       
	echo "ControlManager {  Type : Active  }" >> ~/configuration.config
	echo "CommunicationManager { PhysicalLayer: $COMUNICATION_MANAGER_TYPE" >> ~/configuration.config
	echo "Type : Default" >> ~/configuration.config
	echo "Nodes : $NODE_INFORMATION }" >> ~/configuration.config
	echo "StateManager {Type: $STATE_MANAGER_TYPE" >> ~/configuration.config
	echo "Period : $STATE_MANAGER_PERIOD  }" >> ~/configuration.config
	echo "OutputManager {  Type : $OUTPUT_MANAGER_TYPE" >> ~/configuration.config
	echo "AntiMessages : $OUTPUT_MANAGER_ANTI }" >> ~/configuration.config
	echo "GVTManager {  Type : $GVT_MANAGER_TYPE" >> ~/configuration.config
	echo "Period : $GVT_MANAGER_PERIOD  }" >> ~/configuration.config
	echo "OptFossilCollManager { Type : $FOSSIL_MANAGER_TYPE" >> ~/configuration.config
	echo "CheckpointTime : $FOSSIL_MANAGER_CHKPT" >> ~/configuration.config
	echo "MinimumSamples : $FOSSIL_MANAGER_MIN" >> ~/configuration.config
	echo "MaximumSamples : $FOSSIL_MANAGER_MAX" >> ~/configuration.config
	echo "DefaultLength : $FOSSIL_MANAGER_DEFAULT" >> ~/configuration.config
	echo "AcceptableRisk : $FOSSIL_MANAGER_RISK }" >> ~/configuration.config
	echo "}" >> ~/configuration.config
}

# This function will run the simulations for the given number of samples for the configuration.
function runTest {
  for i in 0 1 2 3 4 5 6 7 8 9
  do
    echo "PHOLD Test" $i
    $PHOLD
  done

  for i in 0 1 2 3 4 5 6 7 8 9
  do
    echo "RAID Test" $i
    $RAID
  done

  for i in 0 1 2 3 4 5 6 7 8 9
  do
    echo "SMMP Test" $i
    $SMMP
  done
}

writeConfiguration
echo "Aggressive Cancellation"
runTest

OUTPUT_MANAGER_ANTI=One
writeConfiguration
echo "One Anti-Message"
runTest

OUTPUT_MANAGER_TYPE=Lazy
OUTPUT_MANAGER_ANTI=Default
writeConfiguration
echo "Lazy Cancellation"
runTest

OUTPUT_MANAGER_TYPE=Dynamic
writeConfiguration
echo "Dynamic Cancellation"
runTest

OUTPUT_MANAGER_TYPE=Aggressive
STATE_MANAGER_TYPE=Periodic
STATE_MANAGER_PERIOD=1
writeConfiguration
echo "Periodic State 1"
runTest

STATE_MANAGER_PERIOD=30
writeConfiguration
echo "Periodic State 30"
runTest

STATE_MANAGER_TYPE=Adaptive
STATE_MANAGER_PERIOD=10
writeConfiguration
echo "Adaptive State"
runTest

STATE_MANAGER_TYPE=Periodic
EVENT_LIST_TYPE=MultiSet
writeConfiguration
echo "MultiSet"
runTest

COMUNICATION_MANAGER_TYPE=MPI
EVENT_LIST_TYPE=Default
writeConfiguration
echo "MPI"
runTest

COMUNICATION_MANAGER_TYPE=TCPSelect
GVT_MANAGER_PERIOD=100
writeConfiguration
echo "Mattern GVT Period 100"
runTest

GVT_MANAGER_PERIOD=10000
writeConfiguration
echo "Mattern GVT Period 10000"
runTest

FOSSIL_MANAGER_TYPE=Cheby
FOSSIL_MANAGER_CHKPT=200
FOSSIL_MANAGER_DEFAULT=100
GVT_MANAGER_PERIOD=1000
writeConfiguration
echo "OFC"

for i in 0 1 2 3 4 5 6 7 8 9
do
  echo "PHOLD Test" $i
  $PHOLD
done

FOSSIL_MANAGER_CHKPT=2000
FOSSIL_MANAGER_DEFAULT=1000
FOSSIL_MANAGER_MAX=500
writeConfiguration
for i in 0 1 2 3 4 5 6 7 8 9
do
  echo "RAID Test" $i
  $RAID
done

FOSSIL_MANAGER_CHKPT=10000
FOSSIL_MANAGER_DEFAULT=2000
FOSSIL_MANAGER_MAX=100
writeConfiguration
for i in 0 1 2 3 4 5 6 7 8 9
do
  echo "SMMP Test" $i
  $SMMP
done
