#!/bin/bash

SIMULATION_TYPE=ThreadedWarp
EVENT_LIST_TYPE=Organized
OBJECT_QUEUE_TYPE=LockedQueue
NUMBER_OF_BUCKETS=5
BUCKET_WIDTH=10
NUMBER_OF_WORKER_THREADS=4
SIMULATION_MANAGER_DOES_WORK=False
COMUNICATION_MANAGER_TYPE=TCPSelect
NODE_INFORMATION=
STATE_MANAGER_TYPE=Periodic
STATE_MANAGER_PERIOD=100
OUTPUT_MANAGER_TYPE=Aggressive
GVT_MANAGER_TYPE=AtomicMattern
GVT_MANAGER_PERIOD=1000 

function writeConfiguration {
	echo "Simulation : $SIMULATION_TYPE" > ~/configuration.config
	echo "TimeWarp {" >> ~/configuration.config
	echo "Scheduler { Type : Default  }" >> ~/configuration.config
	echo "EventList {Type : $EVENT_LIST_TYPE" >> ~/configuration.config
	echo "ObjectQueue {Type : $OBJECT_QUEUE_TYPE" >> ~/configuration.config
	echo "NumberOfBuckets : $NUMBER_OF_BUCKETS " >> ~/configuration.config
	echo "BucketWidth : $BUCKET_WIDTH  }" >> ~/configuration.config
	echo "ThreadControl { WorkerThreadCount : $NUMBER_OF_WORKER_THREADS" >> ~/configuration.config
	echo "SimulationManagerDoesWork : $SIMULATION_MANAGER_DOES_WORK }" >> ~/configuration.config       
	echo "ControlManager {  Type : Active  }" >> ~/configuration.config
	echo "CommunicationManager { PhysicalLayer: $COMUNICATION_MANAGER_TYPE" >> ~/configuration.config
	echo "Type : Default" >> ~/configuration.config
	echo "$NODE_INFORMATION }" >> ~/configuration.config
	echo "StateManager {Type: $STATE_MANAGER_TYPE" >> ~/configuration.config
	echo "Period : $STATE_MANAGER_PERIOD  }" >> ~/configuration.config
	echo "OutputManager {  Type : $OUTPUT_MANAGER_TYPE  }" >> ~/configuration.config
	echo "GVTManager {  Type : $GVT_MANAGER_TYPE" >> ~/configuration.config
	echo "Period : $GVT_MANAGER_PERIOD  }" >> ~/configuration.config
	echo "}" >> ~/configuration.config
}

for j in 0 1 2 3 4
do
for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
do
  NUMBER_OF_WORKER_THREADS=$i
  writeConfiguration
 # ./raidSim -configuration configuration.config -numObjs 8 -simulate LargeRaid

done
done
#./pingpong -configuration configuration.config -numPlayers 100 -numBalls 100000 -numAtOnce 25 
#./smmpSim -configuration configuration.config -numObjs 52 -simulate SMMPDefault
#./pholdSim -configuration thread.config -simulate large.config

